# Generated by Django 2.1.3 on 2019-01-01 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0040_auto_20190101_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_alumnae',
            options={'verbose_name': 'school Alumnae', 'verbose_name_plural': 'school Alumnae'},
        ),
        migrations.AlterModelOptions(
            name='school_anthem',
            options={'verbose_name': 'school Anthem', 'verbose_name_plural': 'school Anthem'},
        ),
        migrations.AlterModelOptions(
            name='school_bakery',
            options={'verbose_name': 'school Bakery', 'verbose_name_plural': 'school Bakery'},
        ),
        migrations.AlterModelOptions(
            name='school_beautification',
            options={'verbose_name': 'school Beautification', 'verbose_name_plural': 'school Beautification'},
        ),
        migrations.AlterModelOptions(
            name='school_biology_lab',
            options={'verbose_name': 'school Biology Lab', 'verbose_name_plural': 'school Biology Lab'},
        ),
        migrations.AlterModelOptions(
            name='school_boarding_department',
            options={'verbose_name': 'school Boarding Department', 'verbose_name_plural': 'school Boarding Department'},
        ),
        migrations.AlterModelOptions(
            name='school_boarding_hod',
            options={'verbose_name': 'school Boarding HOD', 'verbose_name_plural': 'school Boarding HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_bog_chairperson',
            options={'verbose_name': 'school BOG Chairperson', 'verbose_name_plural': 'school BOG Chairperson'},
        ),
        migrations.AlterModelOptions(
            name='school_car_park',
            options={'verbose_name': 'school Car Park', 'verbose_name_plural': 'school Car Park'},
        ),
        migrations.AlterModelOptions(
            name='school_chemistry_lab',
            options={'verbose_name': 'school Chemistry Lab', 'verbose_name_plural': 'school Chemistry Lab'},
        ),
        migrations.AlterModelOptions(
            name='school_christian_union_club',
            options={'verbose_name': 'school Christian Union Club', 'verbose_name_plural': 'school Christian Union Club'},
        ),
        migrations.AlterModelOptions(
            name='school_computer_lab',
            options={'verbose_name': 'school Computer Lab', 'verbose_name_plural': 'school Computer Lab'},
        ),
        migrations.AlterModelOptions(
            name='school_core_values',
            options={'verbose_name': 'school Core Values', 'verbose_name_plural': 'school Core Values'},
        ),
        migrations.AlterModelOptions(
            name='school_debate_club',
            options={'verbose_name': 'school Debate Club', 'verbose_name_plural': 'school Debate Club'},
        ),
        migrations.AlterModelOptions(
            name='school_dining_hall',
            options={'verbose_name': 'school Dining Hall', 'verbose_name_plural': 'school Dining Hall'},
        ),
        migrations.AlterModelOptions(
            name='school_downloads',
            options={'verbose_name': 'school Download', 'verbose_name_plural': 'school Downloads'},
        ),
        migrations.AlterModelOptions(
            name='school_dp_academics',
            options={'verbose_name': 'school DP Academics', 'verbose_name_plural': 'school DP Academics'},
        ),
        migrations.AlterModelOptions(
            name='school_dp_admin',
            options={'verbose_name': 'school DP Admin', 'verbose_name_plural': 'school DP Admin'},
        ),
        migrations.AlterModelOptions(
            name='school_drama_club',
            options={'verbose_name': 'school Drama Club', 'verbose_name_plural': 'school Drama Club'},
        ),
        migrations.AlterModelOptions(
            name='school_events_april',
            options={'verbose_name': 'school events April', 'verbose_name_plural': 'school events April'},
        ),
        migrations.AlterModelOptions(
            name='school_events_august',
            options={'verbose_name': 'school events August', 'verbose_name_plural': 'school events August'},
        ),
        migrations.AlterModelOptions(
            name='school_events_december',
            options={'verbose_name': 'school events December', 'verbose_name_plural': 'school events December'},
        ),
        migrations.AlterModelOptions(
            name='school_events_february',
            options={'verbose_name': 'school events February', 'verbose_name_plural': 'school events February'},
        ),
        migrations.AlterModelOptions(
            name='school_events_january',
            options={'verbose_name': 'school events January', 'verbose_name_plural': 'school events January'},
        ),
        migrations.AlterModelOptions(
            name='school_events_july',
            options={'verbose_name': 'school events July', 'verbose_name_plural': 'school events July'},
        ),
        migrations.AlterModelOptions(
            name='school_events_june',
            options={'verbose_name': 'school events June', 'verbose_name_plural': 'school events June'},
        ),
        migrations.AlterModelOptions(
            name='school_events_march',
            options={'verbose_name': 'school events March', 'verbose_name_plural': 'school events March'},
        ),
        migrations.AlterModelOptions(
            name='school_events_may',
            options={'verbose_name': 'school events May', 'verbose_name_plural': 'school events May'},
        ),
        migrations.AlterModelOptions(
            name='school_events_november',
            options={'verbose_name': 'school events November', 'verbose_name_plural': 'school events November'},
        ),
        migrations.AlterModelOptions(
            name='school_events_october',
            options={'verbose_name': 'school events October', 'verbose_name_plural': 'school events October'},
        ),
        migrations.AlterModelOptions(
            name='school_events_september',
            options={'verbose_name': 'school events September', 'verbose_name_plural': 'school events September'},
        ),
        migrations.AlterModelOptions(
            name='school_fence',
            options={'verbose_name': 'school Fence', 'verbose_name_plural': 'school Fence'},
        ),
        migrations.AlterModelOptions(
            name='school_forest',
            options={'verbose_name': 'school Forest', 'verbose_name_plural': 'school Forest'},
        ),
        migrations.AlterModelOptions(
            name='school_form_four_classes',
            options={'verbose_name': 'school Form Four Classes', 'verbose_name_plural': 'school Form Four Classes'},
        ),
        migrations.AlterModelOptions(
            name='school_form_one_classes',
            options={'verbose_name': 'school Form One Classes', 'verbose_name_plural': 'school Form One Classes'},
        ),
        migrations.AlterModelOptions(
            name='school_form_three_classes',
            options={'verbose_name': 'school Form Three Classes', 'verbose_name_plural': 'school Form Three Classes'},
        ),
        migrations.AlterModelOptions(
            name='school_form_two_classes',
            options={'verbose_name': 'school Form Two Classes', 'verbose_name_plural': 'school Form Two Classes'},
        ),
        migrations.AlterModelOptions(
            name='school_games_department',
            options={'verbose_name': 'school Games Department', 'verbose_name_plural': 'school Games Department'},
        ),
        migrations.AlterModelOptions(
            name='school_games_hod',
            options={'verbose_name': 'school Games HOD', 'verbose_name_plural': 'school Games HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_general_information',
            options={'verbose_name': 'school General Information', 'verbose_name_plural': 'school General Information'},
        ),
        migrations.AlterModelOptions(
            name='school_generator',
            options={'verbose_name': 'school Generator', 'verbose_name_plural': 'school Generator'},
        ),
        migrations.AlterModelOptions(
            name='school_guiding_and_counseling_department',
            options={'verbose_name': 'school Guiding and Counciling Department', 'verbose_name_plural': 'school Guiding and Counciling Department'},
        ),
        migrations.AlterModelOptions(
            name='school_guiding_and_counseling_hod',
            options={'verbose_name': 'school Guiding and Counciling HOD', 'verbose_name_plural': 'school Guiding and Counciling HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_history',
            options={'verbose_name': 'school History', 'verbose_name_plural': 'school History'},
        ),
        migrations.AlterModelOptions(
            name='school_humanities_department',
            options={'verbose_name': 'school Humanities Department', 'verbose_name_plural': 'school Humanities Department'},
        ),
        migrations.AlterModelOptions(
            name='school_humanities_hod',
            options={'verbose_name': 'school Humanities HOD', 'verbose_name_plural': 'school Humanities HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_journalism_club',
            options={'verbose_name': 'school Journalism Club', 'verbose_name_plural': 'school Journalism Club'},
        ),
        migrations.AlterModelOptions(
            name='school_languages_department',
            options={'verbose_name': 'school Languages Department', 'verbose_name_plural': 'school Languages Department'},
        ),
        migrations.AlterModelOptions(
            name='school_languages_hod',
            options={'verbose_name': 'school Languages HOD', 'verbose_name_plural': 'school Languages HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_library',
            options={'verbose_name': 'school Library', 'verbose_name_plural': 'school Library'},
        ),
        migrations.AlterModelOptions(
            name='school_math_department',
            options={'verbose_name': 'school Math Department', 'verbose_name_plural': 'school Math Department'},
        ),
        migrations.AlterModelOptions(
            name='school_math_hod',
            options={'verbose_name': 'school Math HOD', 'verbose_name_plural': 'school Math HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_mission',
            options={'verbose_name': 'school Mission', 'verbose_name_plural': 'school Mission'},
        ),
        migrations.AlterModelOptions(
            name='school_music_club',
            options={'verbose_name': 'school Music Club', 'verbose_name_plural': 'school Music Club'},
        ),
        migrations.AlterModelOptions(
            name='school_muslim_students_club',
            options={'verbose_name': 'school Muslim Students Club', 'verbose_name_plural': 'school Muslim Students Club'},
        ),
        migrations.AlterModelOptions(
            name='school_peace_club',
            options={'verbose_name': 'school Peace Club', 'verbose_name_plural': 'school Peace Club'},
        ),
        migrations.AlterModelOptions(
            name='school_performance',
            options={'verbose_name': 'school Performance', 'verbose_name_plural': 'school Performance'},
        ),
        migrations.AlterModelOptions(
            name='school_physics_lab',
            options={'verbose_name': 'school Physics Lab', 'verbose_name_plural': 'school Physics Lab'},
        ),
        migrations.AlterModelOptions(
            name='school_principal',
            options={'verbose_name': 'school Principal', 'verbose_name_plural': 'school Principal'},
        ),
        migrations.AlterModelOptions(
            name='school_pta_chairperson',
            options={'verbose_name': 'school PTA Chairperson', 'verbose_name_plural': 'school PTA Chairperson'},
        ),
        migrations.AlterModelOptions(
            name='school_science_engineering_club',
            options={'verbose_name': 'school Science Engineering Club', 'verbose_name_plural': 'school Science Engineering Club'},
        ),
        migrations.AlterModelOptions(
            name='school_sciences_department',
            options={'verbose_name': 'school Sciences Department', 'verbose_name_plural': 'school Sciences Department'},
        ),
        migrations.AlterModelOptions(
            name='school_sciences_hod',
            options={'verbose_name': 'school Sciences HOD', 'verbose_name_plural': 'school Sciences HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_site_map',
            options={'verbose_name': 'school Site Map', 'verbose_name_plural': 'school Site Map'},
        ),
        migrations.AlterModelOptions(
            name='school_sports_club',
            options={'verbose_name': 'school Sports Club', 'verbose_name_plural': 'school Sports Club'},
        ),
        migrations.AlterModelOptions(
            name='school_student_council',
            options={'verbose_name': 'school Students Council', 'verbose_name_plural': 'school Students Council'},
        ),
        migrations.AlterModelOptions(
            name='school_teachers',
            options={'verbose_name': 'school Teachers', 'verbose_name_plural': 'school Teachers'},
        ),
        migrations.AlterModelOptions(
            name='school_technicals_department',
            options={'verbose_name': 'school Technicals Department', 'verbose_name_plural': 'school Technicals Department'},
        ),
        migrations.AlterModelOptions(
            name='school_technicals_hod',
            options={'verbose_name': 'school Technical Studies HOD', 'verbose_name_plural': 'school Technical Studies HOD'},
        ),
        migrations.AlterModelOptions(
            name='school_transport',
            options={'verbose_name': 'school Transport', 'verbose_name_plural': 'school Transport'},
        ),
        migrations.AlterModelOptions(
            name='school_updates',
            options={'verbose_name': 'school Update', 'verbose_name_plural': 'school Updates'},
        ),
        migrations.AlterModelOptions(
            name='school_vision',
            options={'verbose_name': 'school Vision', 'verbose_name_plural': 'school Vision'},
        ),
    ]
