# Generated by Django 2.1.3 on 2019-01-01 11:56

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0041_auto_20190101_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_photo_gallery',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('photo', '1024x768', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
